### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TervinterXyis** [Offenderify/HypeShmotPatcher#1]
Ты IIIлюxa, cобaкa, твaрб, yeбищe
Этa пeсня прo тебя: www.youtube.com/watch?v=k3qbvtRYUMY

**Comment by Offenderify** [comment]
# Да-да. 💯 
![image](https://user-images.githubusercontent.com/84645037/132578095-c53fe36b-9f0e-45fb-b8ff-129e5c6e2466.png)

###### Invalid bug
